"""
Build targets that span all Standard libraries.
"""

test_suite(
    name = "string_tests",
    tests = [
        "//libraries/stdlib/clojure:strings_test",
        "//libraries/stdlib/java:strings_test",
        "//libraries/stdlib/python:strings_test",
    ],
)

test_suite(
    name = "small_tests",
    tests = [
        "//libraries/stdlib/clojure:small_tests",
        "//libraries/stdlib/java:small_tests",
        "//libraries/stdlib/python:small_tests",
    ],
)
