"""
This is an example build file which creates a named target for multiple files.
"""

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "documentation",
    srcs = glob(
        ["*.md"]
    ),
)
