"""
Providers for communicating information between dependencies.
"""

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "providers_source",
    srcs = [
        "factor-info.bzl",
        "number-info.bzl",
    ],
    visibility = ["//visibility:public"],
)
