"""
This is an example build file which creates a named target for a single file
"""

filegroup(
    name = "demo",
    srcs = ["hello_world.md"],
    visibility = [
        "//visibility:public",
    ],
)
