"""
Builds consumable libraries of static methods.
"""
load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "strings",
    srcs = ["Strings.java"]
)
