"""
This is an example build file which depends on other packages
"""

filegroup(
    name = "demo",
    srcs = [
        "my_file.md",
        "//hello_world:demo",
        "//hello_world/inner_world:documentation",
    ],
)
